-- MATERIAL (supertipo)
CREATE TABLE MATERIAL (
                          CODIGO         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          TITULO         VARCHAR2(200) NOT NULL,
                          TIPO_MATERIAL  VARCHAR2(15)  NOT NULL,          -- 'LIBRO' | 'REVISTA' | 'AUDIOLIBRO'
                          DIAS_BASE      NUMBER(3)     NOT NULL,
                          DISPONIBLE     CHAR(1)       DEFAULT 'S' NOT NULL,
                          CONSTRAINT CK_MATERIAL_TIPO CHECK (TIPO_MATERIAL IN ('LIBRO','REVISTA','AUDIOLIBRO')),
                          CONSTRAINT CK_MATERIAL_DIAS CHECK (DIAS_BASE > 0),
                          CONSTRAINT CK_MATERIAL_DISP CHECK (DISPONIBLE IN ('S','N'))
);

-- MATERIAL_LIBRO (PK propia y vínculo al MATERIAL)
CREATE TABLE MATERIAL_LIBRO (
                                CODIGO           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                CODIGO_MATERIAL  NUMBER       NOT NULL,
                                AUTOR            VARCHAR2(100) NOT NULL,
                                ANIO             NUMBER(4),
                                ISBN             VARCHAR2(20)  NOT NULL,
                                CONSTRAINT FK_LIBRO_MATERIAL  FOREIGN KEY (CODIGO_MATERIAL) REFERENCES MATERIAL(CODIGO),
                                CONSTRAINT UQ_LIBRO_MATERIAL  UNIQUE (CODIGO_MATERIAL),
                                CONSTRAINT UQ_LIBRO_ISBN      UNIQUE (ISBN),
                                CONSTRAINT CK_LIBRO_ANIO      CHECK (ANIO BETWEEN 0 AND 9999)
);

-- MATERIAL_REVISTA
CREATE TABLE MATERIAL_REVISTA (
                                  CODIGO           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  CODIGO_MATERIAL  NUMBER        NOT NULL,
                                  NUMERO_EDICION   NUMBER(6)     NOT NULL,
                                  PERIODICIDAD     VARCHAR2(30)  NOT NULL,
                                  CONSTRAINT FK_REVISTA_MATERIAL FOREIGN KEY (CODIGO_MATERIAL) REFERENCES MATERIAL(CODIGO),
                                  CONSTRAINT UQ_REVISTA_MATERIAL UNIQUE (CODIGO_MATERIAL),
                                  CONSTRAINT CK_REVISTA_EDICION  CHECK (NUMERO_EDICION >= 0)
);

-- MATERIAL_AUDIOLIBRO
CREATE TABLE MATERIAL_AUDIOLIBRO (
                                     CODIGO            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     CODIGO_MATERIAL   NUMBER        NOT NULL,
                                     NARRADOR          VARCHAR2(100) NOT NULL,
                                     DURACION_MIN      NUMBER(6)     NOT NULL,
                                     LICENCIA_DIGITAL  CHAR(1)       DEFAULT 'N' NOT NULL,
                                     CONSTRAINT FK_AUDIOLIBRO_MATERIAL FOREIGN KEY (CODIGO_MATERIAL) REFERENCES MATERIAL(CODIGO),
                                     CONSTRAINT UQ_AUDIOLIBRO_MATERIAL UNIQUE (CODIGO_MATERIAL),
                                     CONSTRAINT CK_AUDIOLIBRO_DUR      CHECK (DURACION_MIN > 0),
                                     CONSTRAINT CK_AUDIOLIBRO_LIC      CHECK (LICENCIA_DIGITAL IN ('S','N'))
);