-- PRESTAMOS (CRUD de préstamos)
CREATE TABLE PRESTAMOS (
                           CODIGO            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           CODIGO_MATERIAL   NUMBER        NOT NULL,
                           RUT_USUARIO       VARCHAR2(15)  NOT NULL,
                           FECHA_PRESTAMO    DATE          DEFAULT SYSDATE NOT NULL,
                           FECHA_DEVOLUCION  DATE,
                           ESTADO            VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,  -- 'ACTIVO' | 'DEVUELTO'
                           MULTA_APLICADA    NUMBER(10,2)  DEFAULT 0 NOT NULL,
                           DIAS_ATRASO       NUMBER(5)     DEFAULT 0 NOT NULL,
                           CONSTRAINT FK_PREST_MATERIAL  FOREIGN KEY (CODIGO_MATERIAL) REFERENCES MATERIAL(CODIGO),
                           CONSTRAINT FK_PREST_USUARIO   FOREIGN KEY (RUT_USUARIO)     REFERENCES USUARIO(RUT),
                           CONSTRAINT CK_PREST_ESTADO    CHECK (ESTADO IN ('ACTIVO','DEVUELTO')),
                           CONSTRAINT CK_PREST_MULTA     CHECK (MULTA_APLICADA >= 0),
                           CONSTRAINT CK_PREST_ATRASO    CHECK (DIAS_ATRASO >= 0)
);